Ext.define('Chihiro.view.signup.RequiredInfo', {
    extend:'Ext.form.Panel',

    name:'mustForm',
    config:{
        title:'加入千寻',
        items:[
            {
                xtype:'fieldset',
                id:'requiredField',
                defaults:{
                    required:true,
                    allowBlank:false
                },
                items:[
                    {
                        xtype:'emailfield',
                        name:'email',
                        label:'邮箱',
                        placeHolder:'邮箱注册后不可修改',
                        valueType:'email'
                    },
                    {
                        xtype:'passwordfield',
                        name:'password',
                        label:'密码'
                    },
                    {
                        xtype:'passwordfield',
                        name:'confirmPW',
                        label:'确认密码'
                    },
                    {
                        xtype:'numberfield',
                        name:'phone',
                        label:'手机号'
                    },
                    {
                        xtype:'textfield',
                        name:'nickname',
                        label:'昵称'
                    }
                ]
            },
            {
                xtype:'panel',
                layout:'hbox',
                defaults:{
                    xtype:'button',
                    flex:1,
                    width:'40%'
                },
                items:[
                    {
                        text:'注册',
                        ui:'confirm',
                        left:'10%',
                        enabled:false,
                        action:'requiredConfirm'
                    },
                    {
                        text:'返回',
                        ui:'decline',
                        right:'10%',
                        action:'backToSignIn'
                    }
                ]
            }
        ]
    }
});